version: 2
jobs:
  build-and-test:
    docker:
    - image: python3.8
    steps:
      - checkout
      - run:
          command: pip3 install -r requirements.txt
          name: Install deps
      - run:
          command: black sheet.py
          name: Check black
      - run:
          command: flake8 --ignore=W291 sheet.py
          name: Check flake
       
workflows:
  main:
    jobs:
      - build-and-test
