version: 2
jobs:
  build:
    docker:
    - image: python:3.8
    steps:
      - checkout
      - run:
          command: pip3 install -r requirements.txt
          name: Install deps
      - run:
          command: black sheet.py
          name: Check black
      - run:
          command: flake8 --ignore=W291 sheet.py
          name: Check flake
       
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
