version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - name: Install deps 
        run:  pip3 install -r .\requirements.txt
      - name: Check Black
        run: black sheet.py
      - name: Check flake8
        run: flake8 --ignore=W291 sheet.py
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build